"""Shared constants for the async memory governance system."""

EVENT_SCHEMA_VERSION = "1.0"
CANDIDATE_SCHEMA_VERSION = "1.0"
AUDIT_SCHEMA_VERSION = "1.0"
MEMORY_METADATA_VERSION = "1.0"

STATUS_RECEIVED = "received"
STATUS_QUEUE_FAILED = "queue_failed"
STATUS_QUEUED = "queued"
STATUS_EXTRACTING = "extracting"
STATUS_CANDIDATE_READY = "candidate_ready"
STATUS_AUDITING = "auditing"
STATUS_APPROVED = "approved"
STATUS_REVISED = "revised"
STATUS_REJECTED = "rejected"
STATUS_APPLYING = "applying"
STATUS_APPLIED = "applied"
STATUS_DISCARDED = "discarded"
STATUS_FAILED = "failed"

EVENT_STATUSES = (
    STATUS_RECEIVED,
    STATUS_QUEUE_FAILED,
    STATUS_QUEUED,
    STATUS_EXTRACTING,
    STATUS_CANDIDATE_READY,
    STATUS_AUDITING,
    STATUS_APPROVED,
    STATUS_REVISED,
    STATUS_REJECTED,
    STATUS_APPLYING,
    STATUS_APPLIED,
    STATUS_DISCARDED,
    STATUS_FAILED,
)

ACTION_CREATE = "create"
ACTION_UPDATE = "update"
ACTION_MERGE = "merge"
ACTION_LINK = "link"
ACTION_DISCARD = "discard"

ACTIONS = (
    ACTION_CREATE,
    ACTION_UPDATE,
    ACTION_MERGE,
    ACTION_LINK,
    ACTION_DISCARD,
)

AUDIT_APPROVED = "approved"
AUDIT_REVISED = "revised"
AUDIT_REJECTED = "rejected"

AUDIT_DECISIONS = (
    AUDIT_APPROVED,
    AUDIT_REVISED,
    AUDIT_REJECTED,
)

MEMORY_KIND_PREFERENCE = "preference"
MEMORY_KIND_FACT = "fact"
MEMORY_KIND_WORKFLOW = "workflow"
MEMORY_KIND_RELATIONSHIP = "relationship"
MEMORY_KIND_EPHEMERAL = "ephemeral"

MEMORY_KINDS = (
    MEMORY_KIND_PREFERENCE,
    MEMORY_KIND_FACT,
    MEMORY_KIND_WORKFLOW,
    MEMORY_KIND_RELATIONSHIP,
    MEMORY_KIND_EPHEMERAL,
)

QUEUE_MAIN = "memory-events"
QUEUE_REPAIR = "memory-repair"

REPLAY_LOGICAL = "logical"
REPLAY_FULL = "full"

REPLAY_MODES = (
    REPLAY_LOGICAL,
    REPLAY_FULL,
)

